# Copyright 2021 TriggerMesh Inc.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Copyright
copyright: Â© 2021, TriggerMesh

# Project information
site_author: TriggerMesh
site_description: Build your event driven applications in Kubernetes with TriggerMesh APIs. Event sources, targets, filters, splitters, functions, you can do it all.
site_name: TriggerMesh
site_url: https://docs.triggermesh.io
repo_url: https://github.com/triggermesh/docs
edit_uri: edit/main/docs/

extra_css:
  - extra.css
extra_javascript:
  - extra.js

# Page tree
nav:
    - Home: index.md
    - Get started:
      - Quickstart: get-started/quickstart.html
      - Configure autocompletion: get-started/autocompletion.md
      - Concepts: get-started/concepts.md
      - Architecture: get-started/architecture.md
      - Display events in TriggerMesh Console: get-started/triggermesh-console.md
      - From tmctl to Kubernetes: get-started/moving-from-dev-to-K8s.md
      - Event flow and delivery guarantees: get-started/reliabledelivery.md
    - Sources:
      - Amazon CloudWatch: sources/awscloudwatch.md
      - Amazon CloudWatchLogs: sources/awscloudwatchlogs.md
      - Amazon CodeCommit: sources/awscodecommit.md
      - Amazon Cognito Identity Pools: sources/awscognitoidentity.md
      - Amazon Cognito User Pools: sources/awscognitouserpool.md
      - Amazon DynamoDB: sources/awsdynamodb.md
      - Amazon EventBridge: sources/awseventbridge.md
      - Amazon Kinesis: sources/awskinesis.md
      - Amazon S3: sources/awss3.md
      - Amazon SNS: sources/awssns.md
      - Amazon SQS: sources/awssqs.md
      - Azure Activity Logs: sources/azureactivitylogs.md
      - Azure Blob Storage: sources/azureblobstorage.md
      - Azure Event Grid: sources/azureeventgrid.md
      - Azure Event Hubs: sources/azureeventhubs.md
      - Azure IoT Hub: sources/azureiothub.md
      - Azure Queue Storage: sources/azurequeuestorage.md
      - Azure Service Bus Queue: sources/azureservicebusqueue.md
      - Azure Service Bus Topic: sources/azureservicebustopic.md
      - CloudEvents: sources/cloudevents.md
      - Github: sources/github.md
      - Google Cloud Audit Logs: sources/googlecloudauditlogs.md
      - Google Cloud Billing: sources/googlecloudbilling.md
      - Google Cloud Pub/Sub: sources/googlecloudpubsub.md
      - Google Cloud Repositories: sources/googlecloudrepositories.md
      - Google Cloud Storage: sources/googlecloudstorage.md
      - Kafka: sources/kafka.md
      - HTTP Poller: sources/httppoller.md
      - IBM MQ: sources/ibmmq.md
      - OCIMetrics: sources/ocimetrics.md
      - Salesforce: sources/salesforce.md
      - Slack: sources/slack.md
      - Twilio: sources/twilio.md
      - Webhook (HTTP): sources/webhook.md
      - Zendesk: sources/zendesk.md
    - Targets:
      - Alibaba OSS: targets/alibabaoss.md
      - Amazon Comprehend: targets/awscomprehend.md
      - Amazon DynamoDB: targets/awsdynamodb.md
      - Amazon EventBridge: targets/awseventbridge.md
      - Amazon Kinesis: targets/awskinesis.md
      - Amazon Lambda: targets/awslambda.md
      - Amazon S3: targets/awss3.md
      - Amazon SNS: targets/awssns.md
      - Amazon SQS: targets/awssqs.md
      - Azure Event Hubs: targets/azureeventhubs.md
      - Azure Sentinel: targets/azuresentinel.md
      - CloudEvents: targets/cloudevents.md
      - Confluent (deprecated): targets/confluent.md
      - Datadog: targets/datadog.md
      - Elasticsearch: targets/elasticsearch.md
      - Google Cloud Pub/Sub: targets/googlecloudpubsub.md
      - Google Cloud Storage: targets/googlecloudstorage.md
      - Google Cloud Workflows: targets/googlecloudworkflows.md
      - Google Firestore: targets/googlefirestore.md
      - Google Sheets: targets/googlesheets.md
      - Hasura: targets/hasura.md
      - HTTP: targets/http.md
      - IBM MQ: targets/ibmmq.md
      - Jira: targets/jira.md
      - Kafka: targets/kafka.md
      - Logz.io: targets/logz.md
      - Logz.io Metrics: targets/logzmetrics.md
      - Oracle: targets/oracle.md
      - Salesforce: targets/salesforce.md
      - SendGrid: targets/sendgrid.md
      - Slack: targets/slack.md
      - Splunk: targets/splunk.md
      - Tekton: targets/tekton.md
      - Twilio: targets/twilio.md
      - Zendesk: targets/zendesk.md
    - Brokers and Triggers:
      - brokers/index.md
      - Memory Broker: brokers/memorybroker.md
      - Redis Broker: brokers/redisbroker.md
      - Triggers: brokers/triggers.md
      - Trigger filters: brokers/triggerfilters.md
      - Handling failed delivery: brokers/eventdelivery.md
    - Transformations:
      - transformation/index.md
      - JSON Transformation: transformation/jsontransformation.md
      - Function transformations:
        - transformation/functions/index.md
        - Python functions: transformation/functions/pythonfunctions.md
        - NodeJS functions: transformation/functions/nodejsfunctions.md
        - Ruby functions: transformation/functions/rubyfunctions.md
      - Other transformations:
        - JQ Transformation: transformation/other/jqtransformation.md
        - Mulesoft DataWeave Transformation: transformation/other/dataweavetransformation.md
        - XMLtoJSON Transformation: transformation/other/xmltojsontransformation.md
        - XSLT Transformation: transformation/other/xslttransformation.md
    - Operations:
      - Installation:
        - installation/index.md
        - tmctl: installation/tmctl.md
        - Kubernetes YAML: installation/kubernetes-yaml.md
        - Kubernetes Helm: installation/kubernetes-helm.md
        - TriggerMesh and Knative: installation/triggermesh-knative.md
      - Observability:
        - observability/index.md
        - Structured logging: observability/observability-logging.md
        - Telemetry metrics: observability/observability-metrics.md
        - Broker observability: observability/brokerobservability.md
    - Guides:
      - Creating a DLS: guides/creatingadls.md
      - Creating a Wiretap: guides/createawiretap.md
      - Creating a Filter: guides/creatingafilter.md
      - Creating a Splitter: guides/creatingasplitter.md
      - Connecting Clusters: guides/connectingclusters.md
      - Using Kong with TriggerMesh: guides/kong-ingress.md
      - Using Kuma Mesh with TriggerMesh: guides/kuma.md
      - Creating a PrivateLink to TriggerMesh Services: guides/triggermesh-privatelink.md
      - Scaling: guides/scaling.md
      - Webhook to Slack: guides/webhook-to-slack.md
      - Tips for Kubernetes: guides/kubernetestips.md
    - Reference:
      - CLI commands:
         - tmctl: reference/tmctl/tmctl.md
         - tmctl brokers: reference/tmctl/tmctl_brokers.md
         - tmctl config:
           - tmctl config: reference/tmctl/tmctl_config.md
           - tmctl config get: reference/tmctl/tmctl_config_get.md
           - tmctl config set: reference/tmctl/tmctl_config_set.md
         - tmctl create:
           - tmctl create: reference/tmctl/tmctl_create.md
           - tmctl create broker: reference/tmctl/tmctl_create_broker.md
           - tmctl create source: reference/tmctl/tmctl_create_source.md
           - tmctl create target: reference/tmctl/tmctl_create_target.md
           - tmctl create transformation: reference/tmctl/tmctl_create_transformation.md
           - tmctl create trigger: reference/tmctl/tmctl_create_trigger.md
         - tmctl delete: reference/tmctl/tmctl_delete.md
         - tmctl describe: reference/tmctl/tmctl_describe.md
         - tmctl dump: reference/tmctl/tmctl_dump.md
         - tmctl send-event: reference/tmctl/tmctl_send-event.md
         - tmctl start: reference/tmctl/tmctl_start.md
         - tmctl stop: reference/tmctl/tmctl_stop.md
         - tmctl version: reference/tmctl/tmctl_version.md
         - tmctl watch: reference/tmctl/tmctl_watch.md
      - Kubernetes CRDs:
        - reference/index.md
        - Sources: reference/sources.md
        - Targets: reference/targets.md
        - Routing: reference/routing.md
        - Transformation: reference/flow.md
        - Functions: reference/extensions.md
        - Core: reference/eventing.md

theme:
  name: material
  favicon: assets/images/favicon.ico
  logo: assets/images/tmLogo-white.png
  custom_dir: docs/overrides
  analytics:
    gtag: G-V4SM2FT345
  features:
  - content.code.annotate
  - content.tabs.link
  - navigation.indexes
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/triggermesh
      name: TriggerMesh on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/triggermesh/
      name: TriggerMesh on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/triggermesh
      name: TriggerMesh on Twitter
  analytics:
    provider: google
    property: G-N07B164J7T


markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
    - search
