# Copyright 2021 TriggerMesh Inc.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Copyright
copyright: Â© 2021, TriggerMesh

# Project information
site_author: TriggerMesh
site_description: Build your event driven applications in Kubernetes with TriggerMesh APIs. Event sources, targets, filters, splitters, functions, you can do it all.
site_name: TriggerMesh
site_url: https://docs.triggermesh.io
repo_url: https://github.com/triggermesh/docs
edit_uri: edit/main/docs/

extra_css:
  - extra.css
extra_javascript:
  - extra.js

# Page tree
nav:
    - Home: index.md
    - Concepts:
      - '': concepts.md
      - Sources: concepts/sources.md
      - Targets: concepts/targets.md
      - Routing: concepts/routing.md
      - Transformation: concepts/transformation.md
      - Functions: concepts/functions.md
      - TriggerMesh Integration Language: til/Introduction.md
    - Guides:
      - Creating a Source: guides/creatingasource.md
      - Creating a Target: guides/creatingatarget.md
      - Writing a Filter: guides/writingafilter.md
      - Creating a Splitter: guides/creatingasplitter.md
      - Doing a Transformation: guides/doingatransformation.md
      - Writing a Function: guides/writingafunction.md
      - Transforming XML to JSON: guides/xmltojsontransformation.md
      - Transforming XML with XSLT: guides/xslttransformation.md
      - Ingesting External CloudEvents: guides/cloudeventssource.md
      - Using TIL: guides/tilgettingstarted.md
      - Bridges:
        - Webhook to Slack: guides/bridges/webhook-to-slack.md
    - Installation:
      - '': guides/installation.md
      - Using an AWS AMI: guides/installation-ami.md
      - Using Helm: guides/installation-helm.md
      - Tanzu Community Edition: guides/installation-tce.md
    - Integration Language:
      - '': til/Introduction.md
      - CLI: til/Commands.md
      - Language:
        - Concepts: til/Concepts.md
        - Bridge Description Files: til/Bridge-Description-Files.md
        - Component Categories: til/Component-Categories.md
        - Global Settings: til/Global-Settings.md
        - Secret References: til/Secret-References.md
        - Function Expresssions: til/Function-Expressions.md
      - Implementations:
        - Channels: til/Channels.md
        - Routers: til/Routers.md
        - Transformers: til/Transformers.md
        - Sources: til/Sources.md
        - Targets: til/Targets.md
      - Deployment:
        - Output Format: til/Output-Format.md
        - Using Helm: til/Helm.md
        - Using Carvel kapp: til/Carvel-kapp.md
        - Using kubectl: til/Kubectl.md
        - Using kustomize: til/Kustomize.md
    - Reference:
      - '': apis/apis.md
      - Sources: apis/sources.md
      - Targets: apis/targets.md
      - Routing: apis/routing.md
      - Transformation: apis/flow.md
      - Functions: apis/extensions.md
    - Enterprise:
      - '': cloud/index.md
      - Bridge: cloud/bridge.md
      - Sources: cloud/sources/sources.md
      - Targets: cloud/targets/targets.md
      - Secrets: cloud/secrets.md
      - Creating a Service: guides/creatingaservice.md
      - Using the CLI:
        - Installation: tm/install.md
        - Configuration: tm/configuration.md
        - Usage: tm/usage.md
        - Registry: tm/registry.md
        - Serverless Manifest: tm/serverless.md

theme:
  name: material
  favicon: assets/images/favicon.ico
  logo: assets/images/tmLogo-white.png
  custom_dir: docs/overrides
  analytics:
    gtag: G-V4SM2FT345
  features:
  - content.code.annotate
  - content.tabs.link
  - navigation.indexes
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/triggermesh
      name: TriggerMesh on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/triggermesh/
      name: TriggerMesh on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/triggermesh
      name: TriggerMesh on Twitter

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
    - search
    - redirects:
        redirect_maps:
            'sources.md': 'concepts/sources.md'
