site_name: TriggerMesh
repo_url: https://github.com/triggermesh/docs
google_analytics: ['UA-127409524-1', 'docs.triggermesh.io']
nav:
    - Home: index.md
    - Guides:
      - 'Getting Started': guides/gettingstarted.md
      - 'CD': guides/cd.md
      - 'Actions': guides/actions.md
      - 'Bridge': guides/bridge.md
      - 'Secrets': guides/secrets.md
    - Client: 
      - 'Installation': 'tm/install.md'
      - 'Configuration': 'tm/configuration.md'
      - 'Usage': 'tm/usage.md'
      - 'Registry': 'tm/registry.md'
      - 'Serverless Manifest': 'tm/serverless.md'
    - Sources:
      - 'Azure Activity Logs': sources/azureactivitylogs.md
      - 'AWS CodeCommit': sources/awscodecommit.md
      - 'AWS SQS': sources/awssqs.md
      - 'AWS Kinesis': sources/awskinesis.md
      - 'AWS SNS': sources/awssns.md
      - 'AWS DynamoDB': sources/awsdynamodb.md
    - Targets:
      - 'EventBridge': targets/awseventbridge.md
      - 'Twilio': targets/twilio.md
      - 'ElasticSearch': targets/elasticsearch.md
      - 'Confluent': targets/confluent.md
      - 'Tekton': targets/tekton.md
      - 'AWS Lambda': targets/aws.md
    - Cloud: https://cloud.triggermesh.io
    - About: about.md
theme:
  name: mkdocs
